#!/bin/sh

#jetxkbmap us &
xrandr --output HDMI-0 --mode 1920x1080 --output DVI-D-0 --mode 1366x768 --right-of HDMI-0
xset r rate 200 40 &
xsetroot -cursor_name left_ptr &
xset -dpms s off
killall sxhkd
sxhkd &
xmodmap ~/.Xmodmap &
WINEPREFIX=/home/cosmic/d_drive/.wine &

bspc monitor HDMI-0 -d I II III IV V &
bspc monitor DVI-D-0 -d VI VII VIII IX X &

bspc config border_width         0
bspc config window_gap           0
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Alacritty desktop='^1'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Chromium desktop='^6'
bspc rule -a Whatsapp-for-linux desktop='^9'
bspc rule -a Brave-browser-nightly desktop='^2'
bspc rule -a jetbrains-clion desktop='^4'
bspc rule -a Geary desktop='^8'
bspc rule -a okular desktop='^3'
bspc rule -a discord desktop='^9'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a nnn state=floating
bspc rule -a Alacritty_floating state=floating


#bar
$HOME/.config/polybar/launch.sh &
#killall plasmashell &
#plasmashell &

#autostart
nitrogen --restore &
killall picom
picom --experimental-backends &
dunst &

